package org.example.energy.common.enums;

public enum RolEmpleado {
    DIRECTOR_GENERAL,
    DIRECTOR_OPERACIONES,
    DIRECTOR_TECNOLOGIA,
    DIRECTOR_COMERCIAL,
    DIRECTOR_FINANZAS,
    JEFE_EQUIPO_GRANDES_CUENTAS,
    JEFE_EQUIPO_RESIDENCIAL,
    JEFE_MANTENIMIENTO,
    JEFE_RED_DISTRIBUCION,
    JEFE_DESARROLLO,
    JEFE_INFRAESTRUCTURA,
    JEFE_CONTABILIDAD,
    GESTOR_GRANDES_CUENTAS,
    AGENTE_COMERCIAL,
    TECNICO_MANTENIMIENTO,
    TECNICO_RED,
    DESARROLLADOR_SENIOR,
    DESARROLLADOR_JUNIOR,
    DBA,
    CONTABLE
}
